const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const listeners = new Map(), calls = [];
const elements = { statusText: {}, subscriptionError: {} };
const window = { __TAURI__: {
  core: { invoke: async (name, args) => { calls.push([name, args]); if (name === 'vpn_import') throw 'Import failed'; return name === 'vpn_get_state' ? 'connected' : {}; } },
  event: { listen: async (name, fn) => { listeners.set(name, fn); return () => {}; } },
} };
vm.runInNewContext(fs.readFileSync('src/renderer/tauri-bridge.js', 'utf8'), { window, document: { getElementById: id => elements[id] } });
(async () => {
  let state; const off = window.vpnApi.onStateChange(value => { state = value; });
  assert.equal(await window.vpnApi.getState(), 'connected');
  listeners.get('vpn:state')({ payload: 'disconnecting' }); assert.equal(state, 'disconnecting');
  off(); listeners.get('vpn:state')({ payload: 'disconnected' }); assert.equal(state, 'disconnecting');
  let profile; const stopProfiles = window.vpnApi.onProfileChange(value => { profile = value; });
  listeners.get('vpn:profile')({ payload: { profileId: 'server', name: 'Berlin' } });
  assert.equal(profile.name, 'Berlin');
  stopProfiles(); listeners.get('vpn:profile')({ payload: { profileId: 'other', name: 'Paris' } });
  assert.equal(profile.name, 'Berlin');
  let traffic; const stopTraffic = window.vpnApi.onTraffic(value => { traffic = value; });
  listeners.get('vpn:traffic')({ payload: { uploadBytes: 1024, downloadBytes: 2048, uploadBps: 256, downloadBps: 512 } });
  assert.equal(traffic.downloadBps, 512);
  stopTraffic(); listeners.get('vpn:traffic')({ payload: { downloadBps: 1 } });
  assert.equal(traffic.downloadBps, 512);
  assert.equal((await window.vpnApi.connect('abcdef')).ok, true);
  assert.equal(calls.at(-1)[0], 'vpn_connect'); assert.equal(calls.at(-1)[1].profileId, 'abcdef');
  assert.equal(calls.at(-1)[1].dns, 'cloudflare');
  assert.deepEqual([...calls.at(-1)[1].dnsServers], []);
  assert.equal(calls.at(-1)[1].fragmentation, false);
  assert.equal(calls.at(-1)[1].killSwitch, false);
  await window.vpnApi.connect('abcdef', 'quad9'); assert.equal(calls.at(-1)[1].dns, 'quad9');
  await window.vpnApi.connect('abcdef', 'custom', ['192.168.1.1']);
  assert.deepEqual([...calls.at(-1)[1].dnsServers], ['192.168.1.1']);
  await window.vpnApi.connect('abcdef', 'cloudflare', [], true);
  assert.equal(calls.at(-1)[1].fragmentation, true);
  await window.vpnApi.connect('abcdef', 'cloudflare', [], true, true);
  assert.equal(calls.at(-1)[1].killSwitch, true);
  await window.vpnApi.connect('000000000000000000000000', 'cloudflare', [], false, false, ['111111111111111111111111']);
  assert.deepEqual([...calls.at(-1)[1].autoProfileIds], ['111111111111111111111111']);
  await window.vpnApi.connect('abcdef', 'cloudflare', [], false, false, [], 'bypass', ['example.com', 'full:private.example.com']);
  assert.equal(calls.at(-1)[1].routeMode, 'bypass');
  assert.deepEqual([...calls.at(-1)[1].directDomains], ['example.com', 'full:private.example.com']);
  await window.vpnApi.connect('abcdef', 'cloudflare', [], false, false, [], 'bypass', ['geosite:youtube', 'geoip:ru'], 'https://example.com/geoip.dat', 'https://example.com/geosite.dat');
  assert.equal(calls.at(-1)[1].geoIpUrl, 'https://example.com/geoip.dat');
  assert.equal(calls.at(-1)[1].geoSiteUrl, 'https://example.com/geosite.dat');
  assert.equal((await window.vpnApi.importSubscription('https://example.com', 'automatic')).error, 'Import failed');
  assert.equal(calls.at(-1)[1].reason, 'automatic');
  await window.vpnApi.disconnect(); assert.equal(calls.at(-1)[0], 'vpn_disconnect');
  await window.vpnApi.ping('head'); assert.equal(calls.at(-1)[0], 'vpn_ping'); assert.equal(calls.at(-1)[1].pingMethod, 'head');
  await window.vpnApi.publicIp(true); assert.equal(calls.at(-1)[0], 'vpn_public_ip'); assert.equal(calls.at(-1)[1].masked, true);
  await window.vpnApi.deviceInfo(); assert.equal(calls.at(-1)[0], 'vpn_device_info');
  await window.vpnApi.getAutoStart(); assert.equal(calls.at(-1)[0], 'vpn_get_autostart');
  await window.vpnApi.setAutoStart(true); assert.equal(calls.at(-1)[0], 'vpn_set_autostart'); assert.equal(calls.at(-1)[1].enabled, true);
  await window.vpnApi.getLogs(); assert.equal(calls.at(-1)[0], 'vpn_get_logs');
  await window.vpnApi.clearLogs(); assert.equal(calls.at(-1)[0], 'vpn_clear_logs');
  let logLine; const stopLogs = window.vpnApi.onLog(value => { logLine = value; });
  listeners.get('vpn:log')({ payload: 'Xray diagnostic' }); assert.equal(logLine, 'Xray diagnostic'); stopLogs();
  listeners.get('vpn:error')({payload:'Shutdown pending'}); assert.equal(elements.statusText.textContent, 'Shutdown pending');
  console.log('Tauri bridge: state/profile/traffic listeners, unsubscribe, commands, errors passed.');
})().catch(e => { console.error(e); process.exit(1); });
